# Generated by Django 6.0.4 on 2026-04-08 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='公司电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='公司邮箱')),
                ('website', models.URLField(blank=True, verbose_name='公司网站')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='公司地址')),
                ('customer_type', models.CharField(choices=[('enterprise', '企业'), ('individual', '个人'), ('government', '政府机构'), ('organization', '组织')], default='enterprise', max_length=30, verbose_name='客户类型')),
                ('credit_rating', models.CharField(blank=True, max_length=20, verbose_name='信用评级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='名字')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓氏')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='个人电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='个人邮箱')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否为主要联系人')),
                ('role_in_decision', models.CharField(blank=True, choices=[('decision_maker', '决策者'), ('influencer', '影响者'), ('user', '使用者'), ('evaluator', '评估者'), ('gatekeeper', '守门人'), ('other', '其他')], max_length=30, verbose_name='在采购决策中的角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.customer', verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='线索姓名')),
                ('contact_info', models.CharField(max_length=50, verbose_name='联系方式')),
                ('contact_type', models.CharField(choices=[('phone', '手机号'), ('wechat', '微信号'), ('email', '邮箱'), ('other', '其他')], default='phone', max_length=20, verbose_name='联系方式类型')),
                ('source', models.CharField(blank=True, choices=[('website', '官网'), ('offline_event', '线下活动'), ('referral', '推荐'), ('advertisement', '广告'), ('social_media', '社交媒体'), ('exhibition', '展会'), ('cold_call', '陌生拜访'), ('other', '其他')], max_length=30, verbose_name='线索来源')),
                ('status', models.CharField(choices=[('pending', '待联系'), ('contacted', '已联系'), ('converted', '已转化'), ('invalid', '无效')], default='pending', max_length=20, verbose_name='状态')),
                ('first_contact_date', models.DateField(blank=True, null=True, verbose_name='首次联系日期')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='最后沟通日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线索',
                'verbose_name_plural': '线索',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='app_lead_status_a3b0a6_idx'), models.Index(fields=['source'], name='app_lead_source_62ebc5_idx'), models.Index(fields=['contact_info'], name='app_lead_contact_e0cf05_idx')],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', '电话'), ('email', '邮件'), ('meeting', '会议'), ('visit', '拜访'), ('wechat', '微信'), ('sms', '短信'), ('other', '其他')], max_length=20, verbose_name='互动类型')),
                ('subject', models.CharField(max_length=200, verbose_name='互动主题')),
                ('notes', models.TextField(verbose_name='沟通内容')),
                ('interaction_time', models.DateTimeField(verbose_name='互动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.contact', verbose_name='联系人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.customer', verbose_name='客户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='跟进人')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.lead', verbose_name='线索')),
            ],
            options={
                'verbose_name': '互动记录',
                'verbose_name_plural': '互动记录',
                'ordering': ['-interaction_time'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='机会标题')),
                ('stage', models.CharField(choices=[('new_lead', '新线索'), ('requirement', '需求确认'), ('proposal', '方案报价'), ('negotiation', '谈判中'), ('closed_won', '已成交'), ('closed_lost', '已丢失')], default='new_lead', max_length=20, verbose_name='销售阶段')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预计成交金额')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='预计成交日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='app.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售机会',
                'verbose_name_plural': '销售机会',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='产品类别')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='标准单价')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['name'], name='app_product_name_f168ea_idx'), models.Index(fields=['category'], name='app_product_categor_640ae3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='供应商公司名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='主要联系人姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='公司地址')),
                ('credit_rating', models.CharField(blank=True, max_length=20, verbose_name='信用评级')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='是否为首选供应商')),
                ('active_flag', models.BooleanField(default=True, verbose_name='是否正在合作')),
                ('website_url', models.URLField(blank=True, verbose_name='供应商网站')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-is_preferred', 'company_name'],
                'indexes': [models.Index(fields=['company_name'], name='app_supplie_company_663691_idx'), models.Index(fields=['is_preferred'], name='app_supplie_is_pref_5bc150_idx'), models.Index(fields=['active_flag'], name='app_supplie_active__bc8099_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='app_custome_company_0b2994_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='app_custome_custome_21e0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner'], name='app_custome_owner_i_3773a5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['customer'], name='app_contact_custome_7f934b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_primary'], name='app_contact_is_prim_0fb6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='app_contact_email_60d827_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['customer'], name='app_interac_custome_457171_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['contact'], name='app_interac_contact_361536_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['lead'], name='app_interac_lead_id_1426e1_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user'], name='app_interac_user_id_dbd4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['type'], name='app_interac_type_dc5142_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['interaction_time'], name='app_interac_interac_b92a69_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='app_opportu_stage_034edd_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['customer'], name='app_opportu_custome_ccdaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['assigned_to'], name='app_opportu_assigne_9b5ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='app_opportu_expecte_5df68a_idx'),
        ),
    ]
